### ISSUE TITLE
LR workload failed in bigdata scale on spark 2.2

### ISSUE THREAD

**Issue by LifengWang** [Intel-bigdata/HiBench#551]
In bigdata scale, LR workload will fail in spark 2.2 version wtih default hibench configurations. The error is as following. Maybe we can add a new default value of spark.driver.maxResultSizefor for LR like SVD. 
`Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 24 tasks (1030.5 MB) is bigger than spark.driver.maxResultSize (1024.0 MB)
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1517)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1505)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1504)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)`

**Comment by gczsjdy** [comment]
@LifengWang Can you help to add this?
