### ISSUE TITLE
Problem running the sparkbench

### ISSUE THREAD

**Issue by damassh** [Intel-bigdata/HiBench#610]
Hello Guys!

I was trying to run the sparkbench wordCount on my local (Mac OS). I ensured that the hdfs, spark, and yarn are  running. However, I encountered an error in running the `bin/workloads/micro/wordcount/spark/run.sh`.

Here is my error:
`Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
	at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:853)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:223)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:774)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

I'm really stuck at here and hoping anyone can help me. Thanks in advance!

**Comment by cherylLbt** [comment]
How did you solve it?

**Comment by ViniSantosSoftDesign** [comment]
> you

You can go to /HiBench/conf/spark.conf  and replace 

hibench.spark.master       yarn-client

for

hibench.spark.master       yarn
