### ISSUE TITLE
java.lang.ClassNotFoundException: com.intel.hibench.sparkbench.streaming.RunBench

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [Intel-bigdata/HiBench#642]
I got errors like this:
```
20/08/25 21:11:06 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
20/08/25 21:11:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/08/25 21:11:06 WARN SparkSubmit$$anon$2: Failed to load com.intel.hibench.sparkbench.streaming.RunBench.
java.lang.ClassNotFoundException: com.intel.hibench.sparkbench.streaming.RunBench
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:806)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by jchaosun** [comment]
I think you build all like this
`mvn -Dspark=2.4 -Dscala=2.11 clean package`

What I suggest is to try to build a single module
`mvn -Psparkbench -Dmodules -Pstreaming -Dspark=2.4 -Dscala=2.11 clean package`

and then run your workload, e.g.,
`bin/workloads/streaming/identity/spark/run.sh`

Hopefully, it will work in your case.

**Comment by cherylLbt** [comment]
I run ```bin/workloads/streaming/identity/spark/run.sh``` but it shows that "Exception in thread "main" org.apache.spark.SparkException: Broker not in the correct format of <host>:<port> []"

And if I run ``` bin/workloads/micro/wordcount/spark/run.sh```Then I got "java.lang.ClassNotFoundException: com.intel.hibench.sparkbench.micro.ScalaWordCount"

Could you please what's wrong?

**Comment by cherylLbt** [comment]
> I think you build all like this
> `mvn -Dspark=2.4 -Dscala=2.11 clean package`
> 
> What I suggest is to try to build a single module
> `mvn -Psparkbench -Dmodules -Pstreaming -Dspark=2.4 -Dscala=2.11 clean package`
> 
> and then run your workload, e.g.,
> `bin/workloads/streaming/identity/spark/run.sh`
> 
> Hopefully, it will work in your case.

I run ```bin/workloads/streaming/identity/spark/run.sh``` but it shows that "Exception in thread "main" org.apache.spark.SparkException: Broker not in the correct format of : []"

And if I run ```bin/workloads/micro/wordcount/spark/run.sh```, 
Duplicate of #then I got "java.lang.ClassNotFoundException: com.intel.hibench.sparkbench.micro.ScalaWordCount"

Could you please what's wrong?
