### ISSUE TITLE
NoSuchMethodError: com.google.common.base.Preconditions.checkArgument

### ISSUE THREAD

**Issue by WongHuLin** [Intel-bigdata/HiBench#660]
When I excute dataGen.sh for streamingbench, I get an error:

```
NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
	at com.intel.hibench.datagen.streaming.util.CachedData.<init>(CachedData.java:52)
	at com.intel.hibench.datagen.streaming.util.CachedData.getInstance(CachedData.java:43)
	at com.intel.hibench.datagen.streaming.util.KafkaSender.<init>(KafkaSender.java:55)
	at com.intel.hibench.datagen.streaming.DataGenerator$DataGeneratorJob.run(DataGenerator.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) 
```

It seems to be caused by the guava package.

How to solve this problem

**Comment by minmingzhu** [comment]
@WongHuLin  This problem may be caused by the version of Hadoop. Please tell me that what version of Spark and Hadoop are you using and  what command is used to compile Spark.

**Comment by WongHuLin** [comment]
> @WongHuLin This problem may be caused by the version of Hadoop. Please tell me that what version of Spark and Hadoop are you using and what command is used to compile Spark.

The version of Hadoop is 2.10.1, and the version of Spark is 2.4.7. The Spark is decompressed by binary package. The command I compile Hibench is 
`mvn -Dspark=2.4 -Dscala=2.11 clean package`

**Comment by minmingzhu** [comment]
Please check Hadoop jar version from spark jar path (${SPARH_HOME}/jars), whether Hadoop jar version in spark was consistent with your local launched Hadoop version.

**Comment by ghfaha** [comment]
@WongHuLin Did u resolve this issue? I have the same issue! and As much as I am trying to resolve it I am still suffering it :( 
**Please Help me** @minmingzhu @WongHuLin @carsonwang

**Comment by ixzc** [comment]
> 当我为 streamingbench 执行 dataGen.sh 时，出现错误：
> 
> ```
> NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
> 	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
> 	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
> 	at com.intel.hibench.datagen.streaming.util.CachedData.<init>(CachedData.java:52)
> 	at com.intel.hibench.datagen.streaming.util.CachedData.getInstance(CachedData.java:43)
> 	at com.intel.hibench.datagen.streaming.util.KafkaSender.<init>(KafkaSender.java:55)
> 	at com.intel.hibench.datagen.streaming.DataGenerator$DataGeneratorJob.run(DataGenerator.java:116)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748) 
> ```
> 
> 这似乎是由番石榴包引起的。
> 
> 如何解决这个问题呢

Have you solved this problem?

**Comment by ixzc** [comment]
> @WongHuLin你解决了这个问题吗？我有同样的问题！尽管我正在努力解决它，但我仍然在受苦:( **请帮助我** @minmingzhu @WongHuLin @carsonwang

Have you solved this problem?

**Comment by 2018054529** [comment]
@minmingzhu @WongHuLin 
Same issue aroused and I want to know how can I solve this problem D:

**Comment by ixzc** [comment]
> @minmingzhu @WongHuLin Same issue aroused and I want to know how can I solve this problem D:
I have solved all the problems. If you need help, please contact me

**Comment by 2018054529** [comment]
> > I have solved all the problems. If you need help, please contact me
I need ur help, please contact me by april21st@qq.com or let me know how to contact u

**Comment by 2018054529** [comment]
> > @minmingzhu @WongHuLin Same issue aroused and I want to know how can I solve this problem D:
> > I have solved all the problems. If you need help, please contact me

I need your help.please contact me by april21st@qq.com or let me know how to contact u

**Comment by ixzc** [comment]
> april21st@qq.com

ok

**Comment by yemengmeng** [comment]
Can you help me?I need your help.please contact me by 2543532432@qq.com or let me know how to contact u

**Comment by lidehe** [comment]
@ixzc 能否把解决方式分享一下呢(2197947264@qq.com)？我也遇到了这个问题。不胜感激Thanks♪(･ω･)ﾉ

**Comment by lidehe** [comment]
> @ixzc 能否把解决方式分享一下呢([2197947264@qq.com](mailto:2197947264@qq.com))？我也遇到了这个问题。不胜感激Thanks♪(･ω･)ﾉ

@ixzc 
问题已解决，请忽略
Ignore this request. I have already solved the problem.
