### ISSUE TITLE
Error when running dataGen.sh

### ISSUE THREAD

**Issue by cxqzZZ** [Intel-bigdata/HiBench#672]
Ubuntu 18
zookeeper 3.6.3
kafka 2.11-2.30
hadoop 2.7.3
flink 1.10.0

I am working on Flink benchmark adn have successfully run bin/workloads/streaming/wordcount/prepare/genSeedDataset.sh

But when i continue to run  
bin/workloads/streaming/wordcount/prepare/dataGen.sh

problems occured:
log4j:WARN No appenders could be found for logger (org.apache.kafka.clients.producer.ProducerConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
        at com.intel.hibench.datagen.streaming.util.CachedData.<init>(CachedData.java:52)
        at com.intel.hibench.datagen.streaming.util.CachedData.getInstance(CachedData.java:43)
        at com.intel.hibench.datagen.streaming.util.KafkaSender.<init>(KafkaSender.java:55)
        at com.intel.hibench.datagen.streaming.DataGenerator$DataGeneratorJob.run(DataGenerator.java:116)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I have no idea how to run it successfully and to run it successfully counts a lot to me.

**Comment by ghfaha** [comment]
Hello , Did u resolve this , I have the same issue?

**Comment by hrzzz** [comment]
I encoounter the same problem
