### ISSUE TITLE
Error in run: bin/workloads/streaming/identity/spark/run.sh

### ISSUE THREAD

**Issue by cherylLbt** [Intel-bigdata/HiBench#678]
## The error could be this: "Exception in thread "main" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000"

I have googled this error and ti seemed there is an invalid address: ubbo.registry.address=zookeeper://116.1xx.xx.xx:2181. 
This is a new valid one: dubbo.registry.address=zookeeper://xxx.x4.1xx.xx:2181?register=false

I am not sure if your code uses the invalid server. If so, how could I modify it? Thanks a lot for your time.

Here is the Error:
```
ERROR: Spark job com.intel.hibench.sparkbench.streaming.RunBench failed to run successfully.
Hint: You can goto /workspace/my-app/HiBench/report/identity/spark/conf/../bench.log to check for detailed log.
Opening log tail for you:

	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:855)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:930)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:939)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/07/22 03:19:07 INFO util.ShutdownHookManager: Shutdown hook called
21/07/22 03:19:07 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-b295dfd0-ed2f-4538-b222-a3dd3b94a2ae
```
And here is the detailed log:
```
21/07/22 03:19:06 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
21/07/22 03:19:06 WARN zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
21/07/22 03:19:07 INFO zkclient.ZkEventThread: Terminate ZkClient event thread.
21/07/22 03:19:07 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
21/07/22 03:19:07 INFO zookeeper.ZooKeeper: Session: 0x0 closed
21/07/22 03:19:07 INFO zookeeper.ClientCnxn: EventThread shut down
Exception in thread "main" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
        at com.intel.hibench.common.streaming.metrics.MetricsUtil$.createTopic(MetricsUtil.scala:37)
        at com.intel.hibench.sparkbench.streaming.RunBench$.main(RunBench.scala:66)
        at com.intel.hibench.sparkbench.streaming.RunBench.main(RunBench.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:855)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:930)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:939)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/07/22 03:19:07 INFO util.ShutdownHookManager: Shutdown hook called
```

**Comment by cherylLbt** [comment]
I then installer Zookeeper manually (version: 3.6.3). The Error changed into:
```
Exception in thread "main" org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
...
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
```
