### ISSUE TITLE
Building error with one recent patch

### ISSUE THREAD

**Issue by huangshiyou** [Intel-bigdata/HiBench#705]
This patch https://github.com/Intel-bigdata/HiBench/pull/698 causes a building failure on aarch64. 
I reverted the changes in common/pom.xml, then the build works. Could you please take a look at this?

> [ERROR] uncaught exception during compilation: scala.reflect.internal.Types$TypeError
> [ERROR] error: scala.reflect.internal.Types$TypeError: bad symbolic reference. A signature in Logging.class refers to term log4j
> [INFO] in package org.apache which is not available.
> [INFO] It may be completely missing from the current classpath, or the version on
> [INFO] the classpath might be incompatible with the version used when compiling Logging.class.
> [ERROR]         at scala.reflect.internal.pickling.UnPickler$Scan.toTypeError(UnPickler.scala:847)
> [ERROR]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:854)
> [ERROR]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.load(UnPickler.scala:863)
> [ERROR]         at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1489)
> [ERROR]         at scala.tools.nsc.transform.SpecializeTypes$$anonfun$scala$tools$nsc$transform$SpecializeTypes$$normalizeMember$1.apply(SpecializeTypes.scala:798)
> 
> [INFO] hibench 8.0-SNAPSHOT ............................... SUCCESS [  0.113 s]
> [INFO] hibench-common 8.0-SNAPSHOT ........................ FAILURE [  3.954 s]
> [INFO] HiBench data generation tools 8.0-SNAPSHOT ......... SKIPPED
> [INFO] hadoopbench 8.0-SNAPSHOT ........................... SKIPPED
> [INFO] hadoopbench-sql 8.0-SNAPSHOT ....................... SKIPPED
> [INFO] mahout 8.0-SNAPSHOT ................................ SKIPPED
> [INFO] PEGASUS: A Peta-Scale Graph Mining System 2.0-SNAPSHOT SKIPPED
> [INFO] nutchindexing 8.0-SNAPSHOT ......................... SKIPPED
> [INFO] sparkbench 8.0-SNAPSHOT ............................ SKIPPED
> [INFO] sparkbench-common 8.0-SNAPSHOT ..................... SKIPPED
> [INFO] sparkbench micro benchmark 8.0-SNAPSHOT ............ SKIPPED
> [INFO] sparkbench machine learning benchmark 8.0-SNAPSHOT . SKIPPED
> [INFO] sparkbench-websearch 8.0-SNAPSHOT .................. SKIPPED
> [INFO] sparkbench-graph 8.0-SNAPSHOT ...................... SKIPPED
> [INFO] sparkbench-sql 8.0-SNAPSHOT ........................ SKIPPED
> [INFO] sparkbench project assembly 8.0-SNAPSHOT ........... SKIPPED
> [INFO] flinkbench 8.0-SNAPSHOT ............................ SKIPPED
> [INFO] flinkbench-streaming 8.0-SNAPSHOT .................. SKIPPED
> [INFO] gearpumpbench 8.0-SNAPSHOT ......................... SKIPPED
> [INFO] gearpumpbench-streaming 8.0-SNAPSHOT ............... SKIPPED
> [INFO] stormbench 8.0-SNAPSHOT ............................ SKIPPED
> [INFO] stormbench-streaming 8.0-SNAPSHOT .................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  4.268 s
> [INFO] Finished at: 2022-01-29T10:51:07-06:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project hibench-common: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]

**Comment by MeAnkitaDutta** [comment]
> This patch #698 causes a building failure on aarch64. I reverted the changes in common/pom.xml, then the build works. Could you please take a look at this?
> 
> > [ERROR] uncaught exception during compilation: scala.reflect.internal.Types$TypeError
> > [ERROR] error: scala.reflect.internal.Types$TypeError: bad symbolic reference. A signature in Logging.class refers to term log4j
> > [INFO] in package org.apache which is not available.
> > [INFO] It may be completely missing from the current classpath, or the version on
> > [INFO] the classpath might be incompatible with the version used when compiling Logging.class.
> > [ERROR]         at scala.reflect.internal.pickling.UnPickler$Scan.toTypeError(UnPickler.scala:847)
> > [ERROR]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:854)
> > [ERROR]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.load(UnPickler.scala:863)
> > [ERROR]         at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1489)
> > [ERROR]         at scala.tools.nsc.transform.SpecializeTypes$$anonfun$scala$tools$nsc$transform$SpecializeTypes$$normalizeMember$1.apply(SpecializeTypes.scala:798)
> > [INFO] hibench 8.0-SNAPSHOT ............................... SUCCESS [  0.113 s]
> > [INFO] hibench-common 8.0-SNAPSHOT ........................ FAILURE [  3.954 s]
> > [INFO] HiBench data generation tools 8.0-SNAPSHOT ......... SKIPPED
> > [INFO] hadoopbench 8.0-SNAPSHOT ........................... SKIPPED
> > [INFO] hadoopbench-sql 8.0-SNAPSHOT ....................... SKIPPED
> > [INFO] mahout 8.0-SNAPSHOT ................................ SKIPPED
> > [INFO] PEGASUS: A Peta-Scale Graph Mining System 2.0-SNAPSHOT SKIPPED
> > [INFO] nutchindexing 8.0-SNAPSHOT ......................... SKIPPED
> > [INFO] sparkbench 8.0-SNAPSHOT ............................ SKIPPED
> > [INFO] sparkbench-common 8.0-SNAPSHOT ..................... SKIPPED
> > [INFO] sparkbench micro benchmark 8.0-SNAPSHOT ............ SKIPPED
> > [INFO] sparkbench machine learning benchmark 8.0-SNAPSHOT . SKIPPED
> > [INFO] sparkbench-websearch 8.0-SNAPSHOT .................. SKIPPED
> > [INFO] sparkbench-graph 8.0-SNAPSHOT ...................... SKIPPED
> > [INFO] sparkbench-sql 8.0-SNAPSHOT ........................ SKIPPED
> > [INFO] sparkbench project assembly 8.0-SNAPSHOT ........... SKIPPED
> > [INFO] flinkbench 8.0-SNAPSHOT ............................ SKIPPED
> > [INFO] flinkbench-streaming 8.0-SNAPSHOT .................. SKIPPED
> > [INFO] gearpumpbench 8.0-SNAPSHOT ......................... SKIPPED
> > [INFO] gearpumpbench-streaming 8.0-SNAPSHOT ............... SKIPPED
> > [INFO] stormbench 8.0-SNAPSHOT ............................ SKIPPED
> > [INFO] stormbench-streaming 8.0-SNAPSHOT .................. SKIPPED
> > [INFO] ------------------------------------------------------------------------
> > [INFO] BUILD FAILURE
> > [INFO] ------------------------------------------------------------------------
> > [INFO] Total time:  4.268 s
> > [INFO] Finished at: 2022-01-29T10:51:07-06:00
> > [INFO] ------------------------------------------------------------------------
> > [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project hibench-common: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]

I got similar kind pf problem. In my case, the problem occurred due to JAVA version. Earlier I installed Java 11 and Hibench 7.1.1. After downgrading from Java 11 to Java 8, the problem resolved.

**Comment by MeAnkitaDutta** [comment]
I got similar kind pf problem. In my case, the problem occurred due to JAVA version. Earlier I installed Java 11 and Hibench 7.1.1. After downgrading from Java 11 to Java 8, the problem resolved.
