### ISSUE TITLE
Issues with run-sparkbench on Google Cloud Platform (GCP)

### ISSUE THREAD

**Issue by dkdl012** [Intel-bigdata/HiBench#733]
Hi, I build spark clusters using the dataproc provided by GCP; one mater node and three slave nodes.
I want to run HiBench on the above spark environment, however I encounter the issue when I execute this.
<pre> bin/workloads/micro/wordcount/prepare/prepare.sh </pre>

The error logs are these:
<pre>
patching args=
Parsing conf: /home/jieun/HiBench/conf/hadoop.conf
Parsing conf: /home/jieun/HiBench/conf/hibench.conf
Parsing conf: /home/jieun/HiBench/conf/spark.conf
Parsing conf: /home/jieun/HiBench/conf/workloads/micro/wordcount.conf
Traceback (most recent call last):
  File "/home/jieun/HiBench/bin/functions/load_config.py", line 685, in <module>
    load_config(conf_root, workload_configFile, workload_folder, patching_config)
  File "/home/jieun/HiBench/bin/functions/load_config.py", line 217, in load_config
    generate_optional_value()
  File "/home/jieun/HiBench/bin/functions/load_config.py", line 608, in generate_optional_value
    probe_hadoop_examples_jars()
  File "/home/jieun/HiBench/bin/functions/load_config.py", line 392, in probe_hadoop_examples_jars
    examples_jars_candidate_list, "hibench.hadoop.examples.jar")
  File "/home/jieun/HiBench/bin/functions/load_config.py", line 127, in exactly_one_file
    assert 0, "No files found under certain path(s), please set `" + config_name + "` manually"
AssertionError: No files found under certain path(s), please set `hibench.hadoop.examples.jar` manually
/home/jieun/HiBench/bin/functions/workload_functions.sh: line 38: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareWordcount bench
./prepare.sh: line 26: INPUT_HDFS: unbound variable
</pre>

This is my first time running spark and on the cloud environment and I'm not sure how to fix the error. 
Any help would be appreciated. Thanks..

**Comment by dkdl012** [comment]
This error occurs because of the wrong path of "hadoop-mapreduce-examples.jar".

I correct like this:
bin/functions/load_config.py

```<code>
..
def probe_hadoop_examples_jars():
    examples_jars_candidate_apache0 = "/usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar"
..
-------------------------
def probe_hadoop_examples_test_jars():
..
    examples_test_jars_candidate_apache0 = "/usr/lib/hadoop-mapreduce/hadoop-mapreduce-client-jobclient*-tests.jar"
..
```

The hadoop path in the dataproc is defined on "/usr/lib/hadoop-mapreduce".
These variables should be modified.
